### ISSUE TITLE
Bug - Verificar erro quando não consta nenhum colaborador

### ISSUE THREAD

**Issue by leonardocintra-luizalabs** [leonardocintra/programa-inclusao#4]
Verificar erro quando não consta nenhum colaborador cadastrado.

**Comment by leonardocintra-luizalabs** [comment]
![image](https://cloud.githubusercontent.com/assets/10760131/13776313/2f342f86-ea88-11e5-89cb-4c704eb635b2.png)

**Comment by leonardocintra** [comment]
erro ok!
